### ISSUE TITLE
Error detecting remote bundles on Macromates Trunk and Macromates Remote

### ISSUE THREAD

**Issue by jcrosby** [wycats/textmate#2]
GitHub remote bundles are properly detected, but Macromates bundles fail. Output of textmate remote is:
## Macromates Trunk Remote Bundles

svn: PROPFIND request failed on '/svn/Bundles/trunk/Bundles'
svn: PROPFIND of '/svn/Bundles/trunk/Bundles': 301 Moved Permanently (http://macromates.com)
## Macromates Review Remote Bundles

svn: PROPFIND request failed on '/svn/Bundles/trunk/Review/Bundles'
svn: PROPFIND of '/svn/Bundles/trunk/Review/Bundles': 301 Moved Permanently (http://macromates.com)
## GitHub Remote Bundles

Ruby on Rails
Git
...

**Comment by akollegger** [comment]
TextMate bundle repository has moved. Use the patch in this gist:

http://gist.github.com/156760

**Comment by wycats** [comment]
This is fixed on latest.
