### ISSUE TITLE
No "url" in search result. 

### ISSUE THREAD

**Issue by amerine** [wycats/textmate#4]
The api search below:
    http://github.com/api/v1/yaml/search/tmbundle

Does not return a 'url' attribute that line 60 is looking for.
     %[git clone #{e_sh repo['url'].sub('http', 'git') + '.git'} #{e_sh install_bundles_path}/#{e_sh bundle_name}.tmbundle 2>&1]

**Comment by wycats** [comment]
What exactly are you typing to get this error? I cannot reproduce on my machine.

**Comment by amerine** [comment]
Sorry.. I was doing the following:
    textmate install "Ruby Haml" github
